CREATE TABLE IF NOT EXISTS users (
	id BIGSERIAL PRIMARY KEY,
	email VARCHAR (50) NOT NULL,
	password VARCHAR (50) NOT NULL,
	deleted BOOLEAN DEFAULT FALSE NOT NULL
)

CREATE TABLE IF NOT EXISTS kits (
	id BIGSERIAL PRIMARY KEY,
	user_id BIGINT REFERENCES users NOT NULL,
	name VARCHAR (50) NOT NULL
)

CREATE TABLE IF NOT EXISTS kit_items (
	id BIGSERIAL PRIMARY KEY,
	kit_id BIGINT REFERENCES kits NOT NULL,
	name VARCHAR (50) NOT NULL,
	release_form_id INTEGER,
	quantity INTEGER,
	comment VARCHAR (200),
	expiry_date DATE
)